apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-sandbox-prod
spec:
  secretName: {{ .Release.Name }}-sandbox-prod-certificate
  issuerRef:
    name: letsencrypt-prod
  dnsNames:
    - {{ .Release.Name }}-sandbox.featureform.com