name: PR for release branch
on:
  push:
    branches:
      - fake-main
jobs:
  update-release:
    runs-on: ubuntu-latest
    name: release_pull_request
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Latest Release Branch
        id: get_branch
        run: |
          LATEST_BRANCH=$(git branch -r --list "origin/release/*" | sed 's/origin\///' | sort -rV | head -n 1)
          echo "Latest release branch is $LATEST_BRANCH"
          echo "::set-output name=latest_release_branch::${LATEST_BRANCH}"

      # Example of using the output
      - name: Use Latest Branch
        run: echo "The latest release branch is ${{ steps.get_branch.outputs.latest_release_branch }}"

#      - name: Cherry-Pick
#        run: |
#          git config user.name "$(git log -n 1 --pretty=format:%an)"
#          git config user.email "$(git log -n 1 --pretty=format:%ae)"
#          git checkout release/0.11
#          git cherry-pick "$GITHUB_SHA"

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}