name: Docker Build Test
on: [push]

jobs:
  k8s_runner:
    name: Build K8s Runner
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      run: docker build . -t local/k8s_runner:stable -f ./provider/scripts/k8s/Dockerfile
      run: docker build . -t local/k8s_runner_scikit:stable -f ./provider/scripts/k8s/Dockerfile.scikit


#      - name: Build business-layer container
#        uses: docker/build-push-action@v2
#        with:
#          load: true
#          tags: local/k8s_runner:stable
#          context: .
#          file: ./provider/scripts/k8s/Dockerfile
#
#      - name: Build service
#        uses: docker/build-push-action@v2
#        with:
#          load: true
#          tags: local/k8s_runner_scikit:stable
#          context: .
#          file: ./provider/scripts/k8s/Dockerfile.scikit