name: Docker Build Test
on: [push]

jobs:
  k8s_runner:
    name: Build K8s Runner
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Base
        run: docker build . -t local/k8s_runner:stable -f ./provider/scripts/k8s/Dockerfile

      - name: Build scikit
        run: docker build . -t local/k8s_runner_scikit:stable -f ./provider/scripts/k8s/Dockerfile.scikit

      - name: Save
        run: docker save local/k8s_runner_scikit:stable > /tmp/scikit.tar

      - run: ls /tmp

