name: Hosted Testing
on: [push]
concurrency:
  group: ${{ github.head_ref }}-e2e
  cancel-in-progress: true
jobs:
  deploy:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_FF }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_FF }}
      AWS_DEFAULT_REGION: us-east-1
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2

      - name: Check clusters
        run: aws eks list-clusters

      - name: Install Kubectl
        run: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.23.6/bin/linux/amd64/kubectl
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl version --client
          kubectl version --client --output=yaml    

      - name: Install Helm
        run: |
          curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
          sudo apt-get install apt-transport-https --yes
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          sudo apt-get update
          sudo apt-get install helm

      - name: Install IAM Authenticator
        run: |
          curl -o aws-iam-authenticator https://s3.us-west-2.amazonaws.com/amazon-eks/1.21.2/2021-07-05/bin/linux/amd64/aws-iam-authenticator
          chmod +x ./aws-iam-authenticator
          ls $GITHUB_WORKSPACE
          echo "$GITHUB_WORKSPACE"
          echo "$GITHUB_WORKSPACE" >> $GITHUB_PATH
          aws help

      - name: Check auth
        run: aws-iam-authenticator help

      - name: Add kubeconfig
        run: aws eks update-kubeconfig --name cicd-cluster

      - name: Test Kubectl
        run: kubectl get pods

      - name: Helm Install Featureform
        run: helm install featureform ./charts/featureform

      - name: Helm Uninstall Featureform
        if: always()
        continue-on-error: true
        run: helm uninstall featureform
