name: Hosted Testing
on: [push]
concurrency:
  group: ${{ github.head_ref }}-e2e
  cancel-in-progress: true
jobs:
  deploy:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_DEFAULT_REGION: us-west-1
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2

      - name: Install Kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl
          sudo apt-get install -y apt-transport-https
          sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
          echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
          sudo apt-get update
          sudo apt-get install -y kubectl
          
      - name: Install Helm
        run: |
          curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
          sudo apt-get install apt-transport-https --yes
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          sudo apt-get update
          sudo apt-get install helm

      - name: Install IAM Authenticator
        run: |
          curl -o aws-iam-authenticator https://s3.us-west-2.amazonaws.com/amazon-eks/1.21.2/2021-07-05/bin/linux/amd64/aws-iam-authenticator
          chmod +x ./aws-iam-authenticator
          mkdir -p ${HOME}/bin && cp ./aws-iam-authenticator ${HOME}/bin/aws-iam-authenticator
          echo '${HOME}/bin' >> $GITHUB_PATH
          aws-iam-authenticator help
          aws help
#      - name: Install AWS CLI
#        run: |
#          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
#          unzip awscliv2.zip
#          sudo ./aws/install
      - name: Check auth
        run: aws-iam-authenticator help

      - name: Load Kubeconfig
        id: create-json-2
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "config"
          json: ${{ secrets.KUBECONFIG }}

      - name: Add Kubeconfig
        run: |
          mkdir $HOME/.kube
          mv  config $HOME/.kube/config

      - name: Test Kubectl
        run: kubectl get pods
